intrinsics: [[0.58, 0, 0.5],[0, 1.92, 0.5],[0, 0, 1.]]
num_layers_lstm: 2
encoder_channels: [3, 3, 3, 3, 3, 3]
cnn_channels: [9, 3, 3, 3, 3, 3]
generator_channels: [3, 3, 3, 3, 3, 1]
discriminator_channels: [3,3,3,3,3,3]
in_c: 3
h: 128
w: 416
lstm_hidden_size: 10
basepath: ./data
batch_size: 1
epochs: 2
summary_root: './'
pretrained_epoch: False
weights_dir: './weights'
test_seqs: ['19','20','21']
train_seqs: ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18']

